---

- hosts: all
  tasks:
  - name: Create multiple files
    file: 
      path: "{{ /home/karan/ansible_practice}}"
      state: touch
    with_items:
    - test01.txt
    - test02.txt
    - test03.txt
    - test04.txt