--- 
- hosts: all 
  become: yes
  gather_facts: yes 
  tasks: 
  - name: install git on ubuntu nodes
    apt: 
      name: git
      state: present 
    tags: mygit

  - name: install tree
    apt: 
      name: tree
      statte: present 
    tags: mytree
    ignore_errors: yes

    #if any error occur in any task but dont find sol.
    #bt exe remaining task ignore instead of failed
 