--- 
- hosts: all 
  become: yes
  gather_facts: yes 
  tasks: 
  - include_tasks: createfile.yml
  - name: copy index.txt on node
    copy:
       src: index.txt
       dest: /home/karan/

  - name: download remote file (from internet)
    get_url: 
       url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
       dest: /home/ubuntu/jenkins.war
       force_basic_auth: yes
     

