--- 
- hosts: all 
  become: yes 
  gather_facts: yes
  tasks: 
  - name: i want to install webserver
    apt: 
      name: apache2
      state: present
    tags: myapache2

  - name: install tree 
    apt: 
      name: tree 
      state: present 
    tags: mytree

 
 #tags