--- 
- hosts: all 
  become: yes
  gather_facts: yes 
  tasks: 
  - name: install git on ubuntu nodes
    apt: 
      name: git
      state: present 
    tags: mygit

  - name: install tree
    apt: 
      name: tree
      state: present 
    tags: mytree
 
 #tags