--- 
- hosts: 172.31.19.154
  become: yes
  gather_facts: yes 
  tasks: 
  - name: execute cammand on linux
    cammand: hostname -f 
    register: myvariable 

  - name: i want to display first task result 
    debug:
     msg: "{{myvariable}}"