--- 
- hosts: all 
  become: yes 
  gather_facts: yes
  tasks: 
  - name: i want to install webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "RedHat"

  - name: i want to install git
    apt:
      name: "{{k}}"
      state: present 
    when: ansible_os_family == "Debian"