--- 
- hosts: all 
  become: yes 
  tasks: 
   - name: i want to install webserver
     apt: 
      name: apache 
      update_cache: yes
      state: present
      when: ansible_facts['os_family'] == "RedHat"

   - name: i want to install git
     apt:
      name: git  
      state: present 
      when: ansible_facts['os_family'] == "RedHat"



